# Generated by Django 5.2.5 on 2026-01-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_remove_recipe_recipe_id_recipe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_image",
            field=models.ImageField(
                default="recipes/no_picture.png",
                help_text="Upload image or use filename from static/images/recipes/ (e.g., 'recipes/image.jpg')",
                upload_to="recipes",
            ),
        ),
    ]
