# Generated by Django 5.2.6 on 2026-05-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_recipe_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                help_text="Only published recipes are visible to non-staff users.",
                max_length=10,
            ),
        ),
    ]
