# Generated by Django 5.2.6 on 2026-05-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0010_backfill_status_to_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["name"]},
        ),
    ]
